### PR TITLE
Validators can now access context. Forms and submit functions can now setErrors

### PR DESCRIPTION
**Pull request by iyobo**
https://github.com/selbekk/calidation/issues/26
https://github.com/selbekk/calidation/issues/25
https://github.com/selbekk/calidation/issues/28

### CODE REVIEW

**Comment by iyobo** [comment]
Mind the project name and version in package.json.

**Comment by iyobo** [comment]
I suggest creating a branch for me to fork this into, so that it doesn't go directly into your master branch. You may then adjust as needed...especially the package name and versioner.

**Comment by selbekk** [comment]
Hi there!

Thanks for your work. Unfortunately, this PR is a bit too large and unwieldy for me to merge as is. There's a lot of features at once, all of them missing tests, and I'm a bit overwhelmed.

I'll see if I can introduce some of the features you'd suggested though :)

**Comment by iyobo** [comment]
Absolutely. I actually wasn't expecting it to be merged as is. Just as a way for you to see the improvements we use.

**Comment by selbekk** [comment]
I hugely appreciate this. For once the last couple of months, I have a few hours to work on this. Watch out for new versions :)

**Pull request closed without merging**
